### ISSUE TITLE
Add Readme

### ISSUE THREAD

**Issue by himanshumehta1114** [zleight1/webpack-import-map-plugin#3]

**Comment by zleight1** [comment]
I'll try and get to this later this week, for now you can look at the unit tests for some examples of usage.

**Comment by zleight1** [comment]
@himanshumehta1114 Updated with a readme.

**Comment by himanshumehta1114** [comment]
@zleight1 awesome, thanks :)

**Comment by zleight1** [comment]
No problem, if you think of improvements or something that’s needed send a
PR or open a ticket.
